# Generated by Django 5.0.6 on 2025-03-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='textentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Text Entry', 'verbose_name_plural': 'Text Entries'},
        ),
        migrations.AddField(
            model_name='textentry',
            name='entry_id',
            field=models.CharField(default=1, help_text='Unique identifier for the entry', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='text_entries', to='textInfo.category'),
        ),
    ]
