# Generated by Django 5.0.6 on 2025-03-31 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0002_category_alter_textentry_options_textentry_entry_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textentry',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Text Entry', 'verbose_name_plural': 'Text Entries'},
        ),
        migrations.AddField(
            model_name='textentry',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this entry should be displayed (0 = first)'),
        ),
        migrations.AddField(
            model_name='textentry',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this entry should be displayed on the site'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_entries', to='textInfo.category'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='entry_id',
            field=models.CharField(help_text='Auto-generated unique identifier', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
