# Generated by Django 5.0.6 on 2025-03-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0003_alter_textentry_options_textentry_display_order_and_more'),
    ]

    operations = [
    ]
