# Generated by Django 5.0.6 on 2025-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0004_auto_20250331_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='select_option',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', help_text='Select an option from 1 to 6', max_length=1),
        ),
    ]
