# Generated by Django 5.0.6 on 2025-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0005_textentry_select_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textentry',
            options={'ordering': ['unique_id'], 'verbose_name': 'Text Entry', 'verbose_name_plural': 'Text Entries'},
        ),
        migrations.AddField(
            model_name='textentry',
            name='unique_id',
            field=models.CharField(default='default-id', help_text='شناسه یکتا برای کنترل ترتیب نمایش', max_length=50, unique=True),
        ),
    ]
