# Generated by Django 5.0.6 on 2025-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0006_alter_textentry_options_textentry_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='unique_id',
            field=models.CharField(blank=True, help_text='شناسه یکتا برای کنترل ترتیب نمایش (به صورت خودکار ایجاد می\u200cشود)', max_length=50, unique=True),
        ),
    ]
