# Generated by Django 5.0.6 on 2025-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0007_alter_textentry_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
