# Generated by Django 5.0.6 on 2025-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0008_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='description',
        ),
        migrations.AlterField(
            model_name='number',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
