# Generated by Django 5.0.6 on 2025-04-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0009_remove_number_description_alter_number_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('working_hours', models.CharField(max_length=100, verbose_name='ساعت کاری')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'اطلاعات هدر',
                'verbose_name_plural': 'اطلاعات هدر',
            },
        ),
    ]
