# Generated by Django 5.0.6 on 2025-04-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0010_headerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو'),
        ),
    ]
