# Generated by Django 5.0.6 on 2025-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0011_alter_headerinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('location', models.TextField(verbose_name='موقعیت')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='لینک تلگرام')),
                ('aparat_link', models.URLField(blank=True, null=True, verbose_name='لینک آپارات')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='لینک واتساپ')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
            ],
            options={
                'verbose_name': 'اطلاعات فوتر',
                'verbose_name_plural': 'اطلاعات فوتر',
            },
        ),
    ]
