# Generated by Django 5.0.6 on 2025-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0012_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_info/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'اطلاعات معرفی شرکت',
                'verbose_name_plural': 'اطلاعات معرفی شرکت',
            },
        ),
    ]
