# Generated by Django 5.0.6 on 2025-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0013_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمت')),
                ('content', models.TextField(verbose_name='توضیحات خدمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='عکس خدمت')),
                ('service_link', models.URLField(blank=True, null=True, verbose_name='لینک خدمت')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
