# Generated by Django 5.0.6 on 2025-04-07 13:19

import textInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0017_alter_companyinfo_image_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=textInfo.models.get_product_image_filepath),
        ),
    ]

SELECT_CHOICES = [
    ('1','h1'),
    ('2','h2'),
    ('3','h3'),
    ('4','h4'),
    ('5','h5'),
    ('6','h6'),
]
