# Generated by Django 5.0.6 on 2025-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0018_alter_textentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='select_option',
            field=models.CharField(choices=[('1', 'h1'), ('2', 'h2'), ('3', 'h3'), ('4', 'h4'), ('5', 'h5'), ('6', 'h6')], default='1', help_text='Select an option from 1 to 6', max_length=1),
        ),
    ]
