# Generated by Django 5.0.6 on 2025-04-07 14:23

import django.db.models.deletion
import textInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0019_alter_textentry_select_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textentry',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'متن', 'verbose_name_plural': 'متن\u200cها'},
        ),
        migrations.RemoveField(
            model_name='textentry',
            name='select_option',
        ),
        migrations.AddField(
            model_name='textentry',
            name='title_size',
            field=models.CharField(choices=[('1', 'عنوان خیلی بزرگ (h1)'), ('2', 'عنوان بزرگ (h2)'), ('3', 'عنوان متوسط (h3)'), ('4', 'عنوان کوچک (h4)'), ('5', 'عنوان خیلی کوچک (h5)'), ('6', 'عنوان خیلی خیلی کوچک (h6)')], default='1', help_text='اندازه عنوان متن را انتخاب کنید', max_length=1, verbose_name='اندازه عنوان'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_entries', to='textInfo.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش متن (0 = اول)', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='entry_id',
            field=models.CharField(help_text='شناسه یکتا برای هر متن', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='image',
            field=models.ImageField(blank=True, default=textInfo.models.get_default_product_image, null=True, upload_to=textInfo.models.get_product_image_filepath, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='آیا این متن در سایت نمایش داده شود؟', verbose_name='نمایش در سایت'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان متن'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
