# Generated by Django 5.0.6 on 2025-04-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0022_alter_textentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='unique_id',
            field=models.IntegerField(blank=True, help_text='شناسه یکتا برای کنترل ترتیب نمایش', null=True, unique=True),
        ),
    ]
