# Generated by Django 5.0.6 on 2025-04-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0023_alter_textentry_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='main_page_images/', verbose_name='تصویر')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش (0 = اول)', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این تصویر در صفحه اصلی نمایش داده شود؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تصویر صفحه اصلی',
                'verbose_name_plural': 'تصاویر صفحه اصلی',
                'ordering': ['display_order'],
            },
        ),
    ]
