# Generated by Django 5.0.6 on 2025-04-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0024_mainpageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='تصویر پروژه')),
                ('project_id', models.CharField(help_text='شناسه یکتا برای پروژه', max_length=20, unique=True, verbose_name='شناسه پروژه')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش (0 = اول)', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این پروژه در سایت نمایش داده شود؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='textInfo.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['display_order'],
            },
        ),
    ]
