# Generated by Django 5.0.6 on 2025-04-27 17:13

import textInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0026_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default=textInfo.models.get_default_product_image, null=True, upload_to='employees/', verbose_name='عکس'),
        ),
    ]
