# Generated by Django 5.0.6 on 2025-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0027_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ویدیو')),
                ('video_url', models.URLField(verbose_name='لینک ویدیو')),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/', verbose_name='تصویر پیش\u200cنمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['-created_at'],
            },
        ),
    ]
