# Generated by Django 5.0.6 on 2025-04-28 16:39

import textInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textInfo', '0029_video_video_file_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='حداکثر حجم فایل: 100 مگابایت', null=True, upload_to='videos/', validators=[textInfo.models.validate_video_file], verbose_name='فایل ویدیو'),
        ),
    ]
